main: SkywarsGame.Main
version: 0.1
name: Skywars
authors: [Nicronicson]
api-version: 1.13
commands:
  #Skywars
  skywars:
    description: Skywars CCT
    usage: /skywars [Parameters]
    permission: skywars.command.create

  testcommand:
    description: Test
    usage: /testcommand
    permission: skywars.command.create
permissions:
  skywars.command.create:
    default: op